### ISSUE TITLE
Failed retrieving latest ID from API

### ISSUE THREAD

**Issue by Mafiso** [senuido/stash-scanner#5]
HTTP Code: 403 while trying to retrieve URL: http://api.poe.ninja/api/Data/GetStats
Error retrieving latest id from API, bad response

**Comment by AdamMcDougal** [comment]
Looks like the app is dead.

**Comment by Mafiso** [comment]
I know the app is dead. The question is if the author is, as well.

**Comment by senuido** [comment]
fixed in v1.05

**Comment by Mafiso** [comment]
Thank you for the fix, much appriciated.

But also for future reference; please prioritize hotfixes and/or let your user base know. You've probably lost a good amount of said user base since this error was first noticed almost 3 weeks ago.
