### ISSUE TITLE
missing is socket color

### ISSUE THREAD

**Issue by wecode420** [senuido/stash-scanner#6]
where is socket color i cant look up with things what colors i want

**Comment by senuido** [comment]
the app does not provide a way to filter by socket colors right now.
as this is not an issue and more of a feature request, I'm closing this.

**Comment by wecode420** [comment]
then how does poe snipper do it he has it in his program

**Comment by senuido** [comment]
maybe my wording was misleading. I didn't mean its impossible to do. 
I just meant its not supported as you clearly saw.

**Comment by wecode420** [comment]
its kool you dont have a spot to give new ideas so i used this for the idea
unless you got a spot for new ideas i will post there but poe snipper uses
this as well for new ideas

some ideas
1) there needs to be a single button in front of the message you can press
to copy the message off the screen for duel screen users sometimes 6
messages come up and you want the last one real fast
2) add colors for sockets
3)make it so in the filter i can click a item and bring it up in poe trade
with the mods i have in it this way i can make a quick look at its value at
any time not just when it comes up

4)when searching for a item in your filter you should have it highlight all
words that match not just the first one.

if i find more i will let you know but so far love the program man real
nice work.

**Comment by wecode420** [comment]
when i first start the program up some of my filter state override settings
change to blank when i had them disabled or enabled

**Comment by wecode420** [comment]
it would be nice if you had in your prices section the option to override for corrupted or non for each item

you should also add in a paypal button to the program so people can donate

also you need to add in what is confidence level here on the site
